### ISSUE TITLE
New Kit Suggestion: Elytra Kit 

### ISSUE THREAD

**Issue by NO411** [Code-Sploit/kitpvp#2]
# Kit name
Elytra Kit
# Armor type & Enchantments
leather 

# Items & Enchantments
ELytra
50 rockets
1 iron sword
1 gap
20 bread
1 bow 
20 arrows

# Has default items? (Includes 64 steak)
No

# Why do you want this kit to be added
idk

**Comment by Code-Sploit** [comment]
I am assuming that the armor has protection 1 and the sword has sharpness 1?
Please be a bit more descriptive in your next suggestion ;)

**Comment by Code-Sploit** [comment]
I added this @NoahWeiler

**Comment by NO411** [comment]
nice ty!
