### ISSUE TITLE
Add `mod.conf`

### ISSUE THREAD

**Issue by AFCMS** [Code-Sploit/kitpvp#4]
**Describe the bug**
Minetest recently deprecated not providing `mod.conf` :-/

**To Reproduce**
See the log when starting the game :-)

**Expected behavior**
Provide `mod.conf` :-/

**Comment by Code-Sploit** [comment]
https://github.com/Code-Sploit/kitpvp/commit/265859c3bca9b2fbdd96d7c75407dcdafa606b2f

**Comment by AFCMS** [comment]
Nice!
